Update views.py
error
Traceback (most recent call last):
File "/nfs/users/nfs_f/fg12/repos/mlflow-authentication/src/multi_exp_auth.py", line 123, in
experiment_permission = auth_client.create_experiment_permission(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/nfs/users/nfs_f/fg12/repos/mlflow-authentication/.env_mlops/lib/python3.11/site-packages/mlflow/server/auth/client.py", line 266, in create_experiment_permission
resp = self._request(
^^^^^^^^^^^^^^
File "/nfs/users/nfs_f/fg12/repos/mlflow-authentication/.env_mlops/lib/python3.11/site-packages/mlflow/server/auth/client.py", line 37, in _request
resp = http_request_safe(host_creds, endpoint, method, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/nfs/users/nfs_f/fg12/repos/mlflow-authentication/.env_mlops/lib/python3.11/site-packages/mlflow/utils/rest_utils.py", line 170, in http_request_safe
return verify_rest_response(response, endpoint)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/nfs/users/nfs_f/fg12/repos/mlflow-authentication/.env_mlops/lib/python3.11/site-packages/mlflow/utils/rest_utils.py", line 178, in verify_rest_response
raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Missing value for required parameter 'user_name'. See the API docs for more information about request parameters.